// Shared landing-page product catalog — the hardcoded placeholder
// gender/model/color/size domain used by both the public configurator
// (components/landing-hero.tsx) and the pedido/cotización flow
// (app/[locale]/(marketing)/pedido, components/pedido/*). Extracted so
// both can build the same deterministic image path and validate
// submitted values against the same known lists, without duplicating
// them.

export const HERO_ALT_KEYS = {
  male: "imageAltMale",
  female: "imageAltFemale",
} as const;
export type Gender = keyof typeof HERO_ALT_KEYS;

// "colorNavy" -> "navy", "colorSkyBlue" -> "skyBlue" — turns a color's
// translation key into the slug used in its image filename below.
export function colorSlug(nameKey: string): string {
  const rest = nameKey.slice("color".length);
  return rest.charAt(0).toLowerCase() + rest.slice(1);
}

// One photo per gender × model × color combination — 192 placeholder
// PNGs in public/images/products/ (all currently the same Pexels photo),
// generated by a one-off script, not checked-in source photography. Real
// per-combination product photos replace these one file at a time later:
// same filename, real content — no code change needed when that happens.
export function productImagePath(
  gender: Gender,
  model: ModelKey,
  colorNameKey: string,
): string {
  return `/images/products/${gender}-${model}-${colorSlug(colorNameKey)}.png`;
}

export const SIZES = ["XS", "S", "M", "L", "XL", "XXL"] as const;
export type Size = (typeof SIZES)[number];

export const MODELS = [
  { key: "clasico", nameKey: "modelClasico" },
  { key: "slim", nameKey: "modelSlim" },
  { key: "oversize", nameKey: "modelOversize" },
  { key: "cargo", nameKey: "modelCargo" },
  { key: "quirurgico", nameKey: "modelQuirurgico" },
  { key: "deportivo", nameKey: "modelDeportivo" },
  { key: "premium", nameKey: "modelPremium" },
  { key: "ergonomico", nameKey: "modelErgonomico" },
] as const;
export type ModelKey = (typeof MODELS)[number]["key"];

// Garment color swatches, not UI chrome — these represent physical fabric
// colors a scrub actually ships in, so they must stay the same regardless
// of the app's light/dark theme (unlike every other color in this
// project, which comes from app/globals.css's @theme tokens per
// CLAUDE.md section 7). Placeholder sets of commonly available scrub
// colors, split by gender since the real catalogs differ.
export type PaletteColor = { hex: string; nameKey: string };
export const PALETTE: Record<Gender, PaletteColor[]> = {
  male: [
    { hex: "#1F2A44", nameKey: "colorNavy" },
    { hex: "#2551A6", nameKey: "colorRoyal" },
    { hex: "#5B8DB8", nameKey: "colorCeil" },
    { hex: "#12877F", nameKey: "colorTeal" },
    { hex: "#2F4F3E", nameKey: "colorHunterGreen" },
    { hex: "#6B7A3A", nameKey: "colorOlive" },
    { hex: "#3B3B3D", nameKey: "colorCharcoal" },
    { hex: "#1A1A1A", nameKey: "colorBlack" },
    { hex: "#8B8D8F", nameKey: "colorGrey" },
    { hex: "#722F37", nameKey: "colorWine" },
    { hex: "#C3B091", nameKey: "colorKhaki" },
    { hex: "#F5F5F0", nameKey: "colorWhite" },
  ],
  female: [
    { hex: "#1F2A44", nameKey: "colorNavy" },
    { hex: "#7FB3D5", nameKey: "colorSkyBlue" },
    { hex: "#5B8DB8", nameKey: "colorCeil" },
    { hex: "#12877F", nameKey: "colorTeal" },
    { hex: "#8FBFA5", nameKey: "colorMintGreen" },
    { hex: "#4B2E42", nameKey: "colorEggplant" },
    { hex: "#C2185B", nameKey: "colorFuchsia" },
    { hex: "#D98A9A", nameKey: "colorBlushPink" },
    { hex: "#722F37", nameKey: "colorWine" },
    { hex: "#8B8D8F", nameKey: "colorGrey" },
    { hex: "#1A1A1A", nameKey: "colorBlack" },
    { hex: "#F5F5F0", nameKey: "colorWhite" },
  ],
};

export type CityKey = "LA_PAZ" | "SANTA_CRUZ";
export const CITY_KEYS: CityKey[] = ["LA_PAZ", "SANTA_CRUZ"];

export function isModelKey(value: string): value is ModelKey {
  return MODELS.some((model) => model.key === value);
}

export function isSize(value: string): value is Size {
  return (SIZES as readonly string[]).includes(value);
}

export function isCityKey(value: string): value is CityKey {
  return CITY_KEYS.includes(value as CityKey);
}

export function isColorForGender(gender: Gender, nameKey: string): boolean {
  return PALETTE[gender].some((color) => color.nameKey === nameKey);
}

// Picks a random valid {gender, model, color} triple — used by the
// pedido/cotización page's RandomImageCycler when the visitor arrives
// with no selection at all.
export function randomCatalogCombo(): {
  gender: Gender;
  model: ModelKey;
  colorNameKey: string;
} {
  const genders: Gender[] = ["male", "female"];
  const gender = genders[Math.floor(Math.random() * genders.length)];
  const model = MODELS[Math.floor(Math.random() * MODELS.length)].key;
  const palette = PALETTE[gender];
  const colorNameKey = palette[Math.floor(Math.random() * palette.length)].nameKey;
  return { gender, model, colorNameKey };
}
